//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class LinAngMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/LinAng";
        public override string RosMessageName => k_RosMessageName;

        public float lin_x;
        public float lin_y;
        public float lin_z;
        public float ang_x;
        public float ang_y;
        public float ang_z;

        public LinAngMsg()
        {
            this.lin_x = 0.0f;
            this.lin_y = 0.0f;
            this.lin_z = 0.0f;
            this.ang_x = 0.0f;
            this.ang_y = 0.0f;
            this.ang_z = 0.0f;
        }

        public LinAngMsg(float lin_x, float lin_y, float lin_z, float ang_x, float ang_y, float ang_z)
        {
            this.lin_x = lin_x;
            this.lin_y = lin_y;
            this.lin_z = lin_z;
            this.ang_x = ang_x;
            this.ang_y = ang_y;
            this.ang_z = ang_z;
        }

        public static LinAngMsg Deserialize(MessageDeserializer deserializer) => new LinAngMsg(deserializer);

        private LinAngMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.lin_x);
            deserializer.Read(out this.lin_y);
            deserializer.Read(out this.lin_z);
            deserializer.Read(out this.ang_x);
            deserializer.Read(out this.ang_y);
            deserializer.Read(out this.ang_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.lin_x);
            serializer.Write(this.lin_y);
            serializer.Write(this.lin_z);
            serializer.Write(this.ang_x);
            serializer.Write(this.ang_y);
            serializer.Write(this.ang_z);
        }

        public override string ToString()
        {
            return "Linear: " +
            "\nx: " + lin_x.ToString() +
            "\ny: " + lin_y.ToString() +
            "\nz: " + lin_z.ToString() +
            "\nAngular: " +
            "\nx: " + ang_x.ToString() +
            "\ny: " + ang_y.ToString() +
            "\nz: " + ang_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
